package rpc

// A list of supported RPC methods.
const (
	getBestBlockHashMethod         = "getbestblockhash"
	getBlockMethod                 = "getblock"
	getBlockHeightMethod           = "getblockheight"
	getBlockHashMethod             = "getblockhash"
	getBlockTemplateMethod         = "getblocktemplate"
	getConnectionCountMethod       = "getconnectioncount"
	getRawTransactionMethod        = "getrawtransaction"
	getTransactionMethod           = "gettransaction"
	sendTransactionMethod          = "sendtransaction"
	validateRawTransactionMethod   = "validaterawtransaction"
	createAccountMethod            = "createaccount"
	latestLedgerRootMethod         = "latestledgerroot"
	getLedgerProofMethod           = "getledgerproof"
	getCiphertextMethod            = "getciphertext"
	getBlockHashesMethod           = "getblockhashes"
	getBlockHeaderMethod           = "getblockheader"
	getBlocksMethod                = "getblocks"
	getBlockTransactionsMethod     = "getblocktransactions"
	latestBlockMethod              = "latestblock"
	latestBlockHashMethod          = "latestblockhash"
	latestBlockHeaderMethod        = "latestblockheader"
	latestBlockHeightMethod        = "latestblockheight"
	latestBlockTransactionsMethod  = "latestblocktransactions"
	getConnectedPeersMethod        = "getconnectedpeers"
	createRawTransactionMethod     = "createrawtransaction"
	createTransactionMethod        = "createtransaction"
	createTransactionKernelMethod  = "createtransactionkernel"
	decodeRecordMethod             = "decoderecord"
	decryptRecordMethod            = "decryptrecord"
	getRawRecordMethod             = "getrawrecord"
	getRecordCommitmentCountMethod = "getrecordcommitmentcount"
	getRecordCommitmentsMethod     = "getrecordcommitments"
)
